id: P52685A58
initial_creation_type: ocr
source_metadata:
  volumes:
    d947ab1c4c314aff87b8ec4ca95a9a22:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དབུ་མ་རྒྱན་གྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1557
      volume_number: 62
