id: D75C233C1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:39:47+00:00'
last_modified: '2022-05-27T10:01:08.515418+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f41d:
      image_group_id: I1PD95907
      title: དབུ་མ་རྒྱན་གྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1557
      order: 62
      base_file: f41d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
